site_name: GXM BLOG
theme: 
  name: material
  palette:
    # 白天模式
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # 黑夜模式
    - scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  icon: 
    logo: material/github

  language: zh


repo_url: https://gxmgxmgxmgxm.github.io/ic_note/
repo_name: 数字ic学习笔记