site_name: GXM BLOG
site_url: https://gxm.github.io
theme: 
  name: material
  palette:
    # 白天模式
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # 黑夜模式
    - scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  icon: 
    logo: material/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  language: zh

nav:
  - 你好: 你好.md
  - About: index.md
